services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    environment:
      - DB_HOST=db
      - DB_USER=teleup_user
      - DB_PASSWORD=teleup_pass
      - DB_NAME=teleup_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: teleup_db
      MYSQL_USER: teleup_user
      MYSQL_PASSWORD: teleup_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
